name: Update C++ Headers from mapbox/variant

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week on Sunday at midnight
  workflow_dispatch:

jobs:
  update-headers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: main

    - name: Get latest release info
      id: get_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/mapbox/variant/releases/latest)
        echo "tag_name=$(echo $latest_release | jq -r .tag_name)" >> $GITHUB_ENV
        echo "tarball_url=$(echo $latest_release | jq -r .tarball_url)" >> $GITHUB_ENV

    - name: Download release tarball
      run: |
        curl -L ${{ env.tarball_url }} -o release.tar.gz
        mkdir tmp
        tar -xzf release.tar.gz -C tmp --strip-components=1
        rm release.tar.gz

    - name: Patch to strip GCC diagnostic pragmas
      run: |
        find tmp/include/mapbox -type f -name '*.hpp' -exec sed -i '/#pragma GCC diagnostic push/d' {} +
        find tmp/include/mapbox -type f -name '*.hpp' -exec sed -i '/#pragma GCC diagnostic ignored "-Wfloat-equal"/d' {} +
        find tmp/include/mapbox -type f -name '*.hpp' -exec sed -i '/#pragma GCC diagnostic pop/d' {} +

    - name: Copy headers
      run: |
        mkdir -p inst/include
        cp -r tmp/include/* inst/include/
        rm -rf tmp

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: "Update C++ headers from mapbox/variant to release ${{ env.tag_name }}"
        commit-message: "chore(deps): update mapbox/variant to ${{ env.tag_name }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-variant-headers-${{ env.tag_name }}
        body: "Automated update of C++ headers from mapbox/variant release ${{ env.tag_name }}."
        labels: "automated update"
